language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "12"
   - "10"

before_install: npm i -g npm@6.13.4

script:
   - node --version
   - npm --version
   # This is just an example repo, so not enforcing standards
   # - grunt standards
   - commitlint-travis
   - grunt clean build
   - npm run test:ci

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
